### PR TITLE
Add ArcGIS Online login ability for destination. Potential fix for #96

### PR DESCRIPTION
**Pull request by nheminger**
Adding the ability to use ArcGIS Online/enterprise login for the copy
destination portal to fix issues such as #96.

### CODE REVIEW

**Comment by ecaldwell** [comment]
Really nice work @nheminger. I did a moderate amount of testing with it and it appears to be pretty stable. One thing I think we should modify is the login button. It might be confusing to see two different buttons.
screen shot 2015-12-01 at 10 48 01 am


I think an easy workaround that will require minimal modification is to move the enterprise login button next to the existing login button, then toggle which button is hidden/displayed based on the active selection in the radio buttons above. What do you think?

**Comment by ecaldwell** [comment]
This is a little meta, but I've issued a PR to your fork with a proposed change. Take a look and let me know what you think.

**Comment by nheminger** [comment]
Awesome, thanks! Yes, that makes so much more sense. I wasn't paying enough attention to UX on that one.

I am getting an error now though on build. Jshint error:

image

Any ideas? Looks like an anonymous function is created in the loop and Jshint doesn't like it.

**Comment by ecaldwell** [comment]
Just use `grunt -f` to force grunt to ignore that warning and proceed. I still need to address that issue so that jshint is happy.

**Comment by nheminger** [comment]
Great, that worked! That UX is definitely much clearer! Much more :smile: and less :confused:.

**Pull request merged**
