### PR TITLE
Refined build process

### PR DESCRIPTION
**Pull request by ecaldwell**
Lots going on with this update. Would be great to get some eyes on this and have some other people test locally before it gets pulled in. Even though this included a full rewrite of the portal.js library, none of the methods have changed so I think this can be a [`MINOR`](http://semver.org/) release.

  * Heavily refactored and improved the build process. The app will no longer run from the `src` directory. Advantages of the required build process include more concatenation and minification, supporting a config file, and better support for new integrations that require a build (e.g. React).
  * Total rewrite of the portal REST API library. Removed the jquery dependency (in that library), moved to es6 modules, and optimized the build process with [Rollup](http://rollupjs.org/) to produce one minified file for use in this app.
  * Config file makes it easier to customize and deploy this app locally and should support logging in with OAuth in Portals configured with SAML (as described in #115).

### CODE REVIEW

**Comment by nheminger** [comment]
Wow good stuff! :astonished: :thumbsup:

**Comment by jgravois** [comment]
i dont' have keys to the SAML portal i used for testing before, but everything looks good with a new generic arcgis.com appId substituted.

i'll write again if/when i get a hold of valid portal credentials.

**Comment by rwmajor2** [comment]
Good stuff.

**Comment by ecaldwell** [comment]
I've tested against a few different portals including one secured with IWA. Everything works using the OAuth login dialog with one exception. Occasionally, I get a CORS error in the console, but reloading seems to resolve this. Not sure what's causing that, but something to be on the lookout for going forward.

I'm going to go ahead and merge this in.

**Pull request merged**
