### PR TITLE
Add dashboard icon and set workforce project icon

### PR DESCRIPTION
**Pull request by apulverizer**
This adds the dashboard icon as used by ArcGIS Online for `Dashboard` items. It also maps the `Workforce Project` type to show the map icon (which is what AGOL uses).

### CODE REVIEW

**Comment by ecaldwell** [comment]
Don't forget to add the actual icon in `src/assets/images`.

I think it would be time well spent to try and break the item type/icon mapping into its own file to make these kinds of updates easier going forward.

**Comment by apulverizer** [comment]
The `dashboard16.png` icon was added in the commit. 

I wasn't super familiar with code base and thought it was pretty straight-forward to make this update...just my thoughts.

**Comment by ecaldwell** [comment]
I see it now. I somehow overlooked it when viewing the commit the first time. I also forgot we already broke the item types into a json file. Sorry about the false alarms!

**Comment by slibby** [comment]
thanks @apulverizer !

**Pull request merged**
