### PR TITLE
Improved JSON viewing/editing with Ace editor

### LINKED ISSUE #212: Copying Full JSON into Data section does not "work" anymore
In the past I was able to copy all the data out the JSON using ArcGIS online assistant, do some work on it and then paste it back in, Valid and Save and it would work no problem. 

Now it does not without hacking it. If I do a minor edit to the "unedited" json to get the validation save thing to show up, then select all and copy/paste over top it will allow me to save. 

If I don't do this hack it gives me the following  error and just hangs and never loads.

main.min.js:1 Uncaught TypeError: Cannot read property '1' of null
    at validateJson (main.min.js:1)
    at HTMLPreElement.<anonymous> (main.min.js:1)
    at HTMLPreElement.dispatch (jquery-1.10.2.min.js:5)
    at HTMLPreElement.v.handle (jquery-1.10.2.min.js:5)
validateJson @ main.min.js:1
(anonymous) @ main.min.js:1
dispatch @ jquery-1.10.2.min.js:5
v.handle @ jquery-1.10.2.min.js:5

I double check my Json using JSLint and it says it's valid but does not working without the hack mentioned above. 

I think this stackoverflow has a solution for the problem 

https://stackoverflow.com/questions/40554652/uncaught-typeerror-cannot-read-property-1-of-null-in-a-javascript-function

### PR DESCRIPTION
**Pull request by hogpilot**
This PR includes a new integration of [Ace Editor](https://ace.c9.io/) for viewing and editing JSON.  _Highlight.js_ was not meant for editing, and the previous line number integration didn't work very well when adding/deleting lines.  Here are things to test:
- [x] Fixes #212 
- [x] Fixes an unlogged bug where multiple `update` requests were being sent when the same item was saved multiple times
- [x] New capability to expand/collapse JSON
- [x] New logic for tooltip integration with the associated JSON buttons (copy/save/edit).
- [x] New capability to find/replace JSON text (`Ctrl+F`)

For now, a build of this PR is available at [hogpilot/ago-assistant](https://hogpilot.github.io/ago-assistant/build/)

### CODE REVIEW

**Comment by hogpilot** [comment]
I did not remove _js\lib\highlight-8.3.min.js_ (even though it is not used), thoughts?

**Comment by bsvensson** [comment]
The new code editor looks and works great :)

As far as the PR goes, I think most of those ace files are not needed. For example, we're only editing json files (not all file types).

**Comment by hogpilot** [comment]
@bsvensson I agree, and only found 4 files used in my testing:
- js/lib/ace/ace.js
- js/lib/ace/mode-json.js
- js/lib/ace/theme-tomorrow.js
- js/lib/ace/worker-json.js

I left the rest of them in there in case somewhere down the line, other ace options are utilized.  I went back and forth about the proper approach for this scenario, but don't feel strongly one way or the other.   For now, the full ace library source code is in there...

I'm open for thoughts on which approach to take.  The current approach is safe, and while it increases the repo and deployment size, it has no impact on the client network traffic.  I was afraid some other ace call might break things down the line if I removed a file that didn't come up in my testing.

**Comment by hogpilot** [comment]
Case and point, _Find/Replace_ (Ctrl-F) triggers an additional file (thanks @bsvensson , i didn't know you could do that):
- js/lib/ace/ext-searchbox.js

**Comment by hogpilot** [comment]
Another note on which Ace files to include.  Pressing `Ctrl+,` brings up a settings menu.  You can change options/themes there, which will dynamically load additional ace files.  It might be nice to leave that feature (give a try to see what I mean), which might not allow us to trim down the ace files.  Or, we could just include the 4 or 5 files that @bsvensson identified and disable the settings menu.

I'm open to feedback if anyone feels strongly one way or another.

**Comment by slibby** [comment]
@hogpilot seeing a few strange characters on one item - highlighted in red:
image

**Comment by hogpilot** [comment]
@slibby interesting.  Ace is telling you that there is an invalid or invisible character there.  It turns out, this is because the JSON contains `\u00A0` (or `&nbsp`, or character code 160) in the text.  This is due to the ArcGIS Online WYSIWYG editor adding a non-breaking space.  

Since this is not printable (other than as a space), Ace is differentiating it for you.  I agree that red is not ideal, so I can override the CSS.  How does this look?
image

**Comment by hogpilot** [comment]
@slibby @bsvensson  thanks for the feedback.  The latest commit includes the changes you mentioned:
- [ ] Remove unused Ace files
- [ ] Disable Ace settings menu `Ctrl+,`
- [ ] Switch theme to dark background when editing
- [ ] Change CSS for `&nbsp` character so it is not red

I think this is ready once testing is complete (@slibby? @rwmajor2? @ecaldwell?), let me know if you have questions.

**Comment by hogpilot** [comment]
Can someone else test https://hogpilot.github.io/ago-assistant/build/ in IE to see if they get weird cursor/text-selection behavior?  If so, anybody have an idea of what CSS is the culprit?  Thanks.

**Comment by bsvensson** [comment]
> Can someone else test https://hogpilot.github.io/ago-assistant/build/ in IE to see if they get weird cursor/text-selection behavior? 

Yes, the cursor becomes the `cursor-move` cursor after clicking the edit/pen icon to go into Edit mode. Weird.

Double-clicking to select text does the right thing (functionally), but displays a selection box of sorts in the wrong place. Weird.

I don't see the same issue in IE11 for neither the JSAPI sandbox, nor [the Ace kitchen sink](https://ace.c9.io/build/kitchen-sink.html).

> If so, anybody have an idea of what CSS is the culprit? 

Nope :(

**Comment by hogpilot** [comment]
@bsvensson Thanks for checking.  I found the culprit and fixed it in the latest commit.  It had to do with our use of `contenteditable` attribute as it pertains to the `Enter` keypress.  Apparently, IE didn't like me using that attribute on a `div` and when I added it to the Ace editor during edits, it threw off the CSS.  Fix was to stop using the `contenteditable` attribute and instead rely on the `.getReadOnly()` operation of Ace.

**Comment by hogpilot** [comment]
**Note**:  In my latest commit, I also snuck a few changes into `templates.html` that I found while searching for IE issue.  These changes are not related to the PR, other than the fact that they are obvious errors that should be fixed (my opinion at least).

**Comment by ecaldwell** [comment]
>I also snuck a few changes into templates.html that I found

Nice find! Maybe this could be addressed with better linting.

**Comment by setldsolutions** [comment]
Without reading through all this:  are we saying #212 and #213 are fixed (since both threads are closed)?  E.g. the pasting of JSON back from notepad can now deal with the window's requirement for numbered lines?  If so, that's great.

However, there is still another related issue.  Simply hitting the pencil, so that I can CTRL A, CTRL C and CTRL V into Notepad ++ takes wayyyyyyyyy longer than it used to.  It used to take maybe 30 seconds to give me access to the text - now, it takes 15 browser waits and maybe 30 minutes.

**Comment by slibby** [comment]
@setldsolutions yes, both of those should be fixed in the latest code here on github, which has not yet been deployed to https://ago-assistant.esri.com. In the interim, you can try this build of the app first and see if you still have that delay: https://hogpilot.github.io/ago-assistant/build/ -- we are working on getting the latest build deployed.

**Comment by setldsolutions** [comment]
Thanks Sam.

**Comment by setldsolutions** [comment]
Confirmed working - no hitting the pencil to start editing necessary.

Simply click in the box, wait a sec, CTRL A, CTRL C, CTRL V to Notepad ++ --- 91k+ lines of JSON in 2 seconds. 

Thanks again!

**Comment by setldsolutions** [comment]
Seems to be a new issue, both with prod and with build.  CTRL A, then Backspace used to clear the box.  Now, CTRL A really wants to show me the end of the code and ignore Backspace or Delete keys.

**Pull request merged**
