### PR TITLE
Documentation mitigation for #176

### PR DESCRIPTION
**Pull request by nheminger**

### CODE REVIEW

**Comment by jgravois** [comment]
rollup _doesn't_ need to be installed globally if you just invoke the grunt command from `npm run build`.  it'd be better to document that.

**Comment by nheminger** [comment]
Good catch. I'm not as familiar with that. Is `npm run build` a way to invoke grunt or it is invoking npm? Would it be recommended for users to run `npm run build` over `grunt`?

**Comment by jgravois** [comment]
> Would it be recommended for users to `run npm run build` over `grunt`?

exactly.  npm scripts are defined in [`package.json`](https://github.com/Esri/ago-assistant/blob/8c72ba14ffd8ba23402f95be3cb835cfc15e3fc4/package.json#L64) and in this case provide nothing more than a little encapsulation.

more info here:
https://blog.jayway.com/2014/03/28/running-scripts-with-npm/

**Comment by jgravois** [comment]
@rwmajor2 i had requested changes on this pull request. any reason in particular you wanted to include instructions for installing rollup globally in our doc?

**Pull request merged**
