### PR TITLE
linting fix

### PR DESCRIPTION
**Pull request by jgravois**
so that its no longer necessary to use `grunt --force`

cc/ @jyaistMap

### CODE REVIEW

**Comment by ecaldwell** [comment]
Thanks for addressing this @jgravois! This one has been nagging me for a while.

I'm getting an error at line 1109: `serviceData is not defined` when I try to do a Full Copy on a feature service. Are you seeing that too?

**Comment by jgravois** [comment]
> Are you seeing that too?

absolutely.  sorry for submitting a PR with an obviously busted *fix*!

i made a correction (bear in mind that i only tested the approach with a feature service with <1000 records), and it seems like a decent alternative to just resolve all the query promises together and then do the same with the calls to `addFeatures`

another option would be to just force jshint to ignore the error locally for now so other folks don't run into the error when they first touch the project

```js
/*jshint -W083 */
/*jshint +W083 */
```

happy to chat more if it'd be helpful.

**Comment by ecaldwell** [comment]
> another option would be to just force jshint to ignore the error locally for now so other folks don't run into the error when they first touch the project

Maybe that's the smarter approach. I don't think that particular error is all that terrible (almost seems inevitable with async calls). Can we set a flag in `Gruntfile.js` or maybe even `package.json` to override it and add a comment to the code in question indicating it will cause an error if that flag is removed?

**Comment by jgravois** [comment]
i just pushed up another commit to selectively ignore the warning.  i agree that the error isn't *terrible*.  that said, you do open yourself up to the possibility of unexpected behavior if any variables accessed in the anonymous callback function within the loop change out from underneath you. 

https://jslinterrors.com/dont-make-functions-within-a-loop

the approach i outlined previously (for aggregating individual promises) could be worth revisiting, but i don't blame you if you want to wait until you actually 'get bit'.

**Comment by ecaldwell** [comment]
Looks good. Would you mind squashing the two commits so it's just showing the final agreed upon change?

**Comment by jgravois** [comment]
maintainers can squash/merge directly in github now!

https://github.com/blog/2141-squash-your-commits

**Comment by ecaldwell** [comment]
> maintainers can squash/merge directly in github now!

Mind blown. 💣  That's certainly going to be handy going forward. Thanks again for taking care of this one!

**Pull request merged**
