### PR TITLE
Portal login OAuth support and enhancements

### PR DESCRIPTION
**Pull request by hogpilot**
Summary of changes:
- Refactored the portal login form to include OAuth (both source and destination)
- Added capability to store previous portals in localStorage (adding a drop-down to the portal url input)
- Added capability to parse portal url and appid from the app url parameters
- Added item id and owner to content buttons (for search results and other item listing buttons)
- Added portal name and user info to top of 'itemsArea' and 'dropArea'

Potentially addresses #115 and #90

### CODE REVIEW

**Comment by hogpilot** [comment]
You can view a live version of these updates here: https://hogpilot.github.io/ago-assistant/build/

This PR is ready for assignment and testing

**Comment by hogpilot** [comment]
To test portal and appid parsing from url, use the format:
https://hogpilot.github.io/ago-assistant/build/?portal=<portalUrl>&appid=<appid>

**Comment by rwmajor2** [comment]
@hogpilot This looks good.  Let's make sure we do some good testing of this over the next few days and we will roll this in and also push up to the public version.

I like adding owner to Search Results.  Do you think itemid is bringing value there?  I do not.  Just makes it cluttered.

One minor note.  I realize you did this for a particular customer, but maybe we can be a little more consistent in how we offer "More Info" links in the new refactor UI.  Not a big deal, but I rather see the same "More Info" link on each tab for consistency.

image

image

image

**Comment by ecaldwell** [comment]
>I like adding owner to Search Results. Do you think itemid is bringing value there? I do not. Just makes it cluttered. @rwmajor2 

This was actually a requested enhancement in #90. I agree that it's a little cluttered. What if it presented a shortened version just like git does with commit ids? This would also allow you to increase the font size to make them more legible.

**Comment by slibby** [comment]
Tested Successfully:

- Direct Login to ArcGIS Online
- Direct Login to Portal
- IWA Login to Portal with IWA
- SAML ogin to Portal with oAuth
- Copy content to my own content using a SAML-enabled Portal
- Copy from SAML-enabled Portal to SAML-enabled Online (Failed once, works on new reload)
- Copy from SAML-enabled Portal to SAML-enabled Portal

Issues:
- when copying a web map to my own account or another account, the item ID for the new item appears the same as the old Item ID:
image



Additional Fixes:
- Add Portal URL or ArcGIS Online URL to top of left-side column 
image
- change "hint" text for Portal Login from "https://myporta.com" to "https://myportal.domain.com/<webadaptor>"
- make drop-down of Local Storage Portal URLs full-width under the text entry box. 
- add "Current user: " to username on left column
image
- if you select a portal from localStorage with an appID, then switch to ArcGIS Online and back to Portal, the AppID remains in the dialog
 - add mouseover text to item icons with item Type and item ID in the mouseover
- Use FullName in upper right corner instead of username

**Comment by ecaldwell** [comment]
Thanks for testing all of that @slibby! 🍺 

>when copying a web map to my own account or another account, the item ID for the new item appears the same as the old Item ID
That's a result of the way the item is cloned in the DOM. It probably makes sense to just clear that property in the clone.

**Comment by hogpilot** [comment]
@rwmajor2 @slibby @ecaldwell I made the changes/enhancements you mentioned above in your comments.  Please take another look and let me know if you have additional assignments for this PR.

**Comment by hogpilot** [comment]
Latest commits include a few new changes (thanks to @slibby and @jmirmelstein ):
- [x] Line numbers on JSON view
- [x] Live feedback/linting of JSON when editing
- [x] Possible to copy item with same name into same folder (by appending "-Copy")
- [x] A few additional CSS tweaks for UI (thanks to @asizer )

**Comment by ecaldwell** [comment]
These are really great enhancements! I played around with it a bit and everything seems to be behaving well. I like that you added the "copying" svg to the destination item. It's a little small...can you easily move it to be right aligned in the button the way the status is when deep copyi a feature service?

Aside from that, I'd say this is ready to be merged in. What say you @rwmajor2? Thanks for all the work on this @hogpilot!

**Comment by slibby** [comment]
This also closes #199

**Comment by ecaldwell** [comment]
The new dev tooling is in so we're ready to merge this. There are two conflicts preventing a clean merge. Simply unstaging config.json and package.json from this PR should resolve it.

- You pushed a new `appId` in `config.json` which we would not have wanted to merge anyway.
- The edit in `package.json` was a minor linting correction (in a no longer included dependency).

Can you unstage those two and push to your branch? Then the changes should show up here.

**Comment by hogpilot** [comment]
@ecaldwell @rwmajor2 there should be no conflicts now

**Comment by ecaldwell** [comment]
I'm seeing a clean merge option now. Thanks @hogpilot! 

@rwmajor2 Recommend you do this as a squash and merge to consolidate the commits.

**Comment by hogpilot** [comment]
This includes the same fix in #180 recommend closing both together

**Pull request merged**
